// IT'S A SERVER!

//API ROUTES
    //CRUD :)
        //CREATE - POST RESERVATIONS
            //FS
        //READ - GET RESERVATION OBJECTS
        //UPDATE
        //DELETE
//HTML ROUTES
    //GET, RES.SENDFILE TABLES
    //GET, RES.SENDFILE RESERVATIONS